spring:
  application:
    name: collabo_creator_boot
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://117.52.20.52:3306/collabo
    username: manna
    password: manna20@#

    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      connection-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MariaDB103Dialect
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 10
        format_sql: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB
      location: upload
      enabled: true

org:
  example:
    accessTime: 60
    refreshTime: 216000
    alwaysNew: true
    upload:
      path: upload

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket : oz-wizard-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false

kakao:
  api:
    key: ${KAKAO_API_KEY}

logging:
  level:
    org.springframework.security.web: TRACE
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE